---
# tasks file for Nagios_ubuntu
- name: Install the dependencies for nagios
  apt:
    name:
    - autoconf
    - gcc
    - libc6
    - make
    - wget
    - unzip
    - apache2
    - php
    - libgd-dev
    state: latest
- name: Stop the firewall service
  service:
    name: ufw
    state: stopped
    enabled: no

- name: Download and unpack nagios
  unarchive:
    src: https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.4.5.tar.gz 
    dest: /tmp/
    remote_src: yes
  register: nagios_source

- name: Create the Nagios file
  shell: cd /tmp/nagioscore-nagios-4.4.5; sh /tmp/nagioscore-nagios-4.4.5/configure --with-httpd-conf=/etc/apache2/sites-enabled
  register: make_file
  when: nagios_source.changed

- name: Compile the files related to Nagios
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: all
  when: make_file.changed

- name: Create the user and group called nagios
  make: 
    chdir: /tmp/nagioscore-nagios-4.4.5/
    target: install-groups-users
  when: make_file.changed

- name: Add apache(www-data) to nagios group
  user:
    name: www-data
    group: nagios
    append: yes

- name: Install the nagios core
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install
  when: make_file.changed

- name: Install daemon for nagios
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-daemoninit
  when: make_file.changed

- name: Install the command mode for nagios
  shell: cd /tmp/nagioscore-nagios-4.4.5; sudo make install-commandmode
  when: make_file.changed

- name: Install the configuration file
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-config
  when: make_file.changed

- name: Install the Apache config files
  make:
    chdir: /tmp/nagioscore-nagios-4.4.5
    target: install-webconf
  register: install_webconf
  when: make_file.changed

- name: Enable cgi module for Apache2
  apache2_module:
    state: present
    name: cgi

- name: enable rewrite module for Apache2
  apache2_module:
    state: present
    name: cgi

- name: Restart the Apache2 service
  service:
    name: apache2
    state: restarted
  when: install_webconf.changed

- name: Start and Enable nagios service
  service:
    name: nagios
    state: started
    enabled: yes
  when: install_webconf.changed
